sudo: required
services:
  - docker
# Use generic image to cut start-up time
language: generic
env:
  CST_REF: v1.8.0
  HADOLINT: "/tmp/hadolint"
before_install:
  - docker build -t myimage .
script:
  bash scripts/test.sh

